version: "3"

services:
  search:
    ports:
      - "9200:9200"
    restart: always
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
